title: SimpleID
description: 'SimpleID is a simple, personal OpenID provider written in PHP.'

collections:
    docs:
        output: true

permalink: /:categories/:year/:month/:title

exclude: 
    - .rvmrc
    - .rbenv-version
    - README.md
    - Gemfile
    - vendor

highlighter: pygments

gems:
    - jekyll-redirect-from
